### ISSUE TITLE
1.11 requires mod ID change

### ISSUE THREAD

**Issue by asiekierka** [OpenMods/NotEnoughCodecs#6]
Specifically, mod IDs are enforced to be lowercase - "notenoughcodecs" vs the current "NotEnoughCodecs".

How should I/we go about this?

**Comment by boq** [comment]
I guess other mods may depend on exact modid, so changing this for whole 1.8-1.10.2 range is out of question.

So I will just change modid and reset range to `[1.11,1.12)`, while keeping old one in branch. It's not like there are frequent updates to this mod.

**Comment by asiekierka** [comment]
Yes. Charset (I think the only mod using NotEnoughCodecs at this point?), for instance, relies on exact modID for detection.

**Comment by boq** [comment]
Ok, managed to keep everything in single branch with only minor hackery. Releasing.
